[tools]
fd = "latest"      # used by lazyvim / neovim
gh = "latest"
lazygit = "latest" # used by lazyvim / neovim??
# luajit = "latest"  - doesn't build on pi?
python = "3.12"
ripgrep = "latest"
uv = "0.12"

[settings]
idiomatic_version_file_enable_tools = ["node", "python"]
