[tools]
python = "3.12"
uv = "0.12"

[settings]
experimental = true
python.uv_venv_auto = "create|source"

[hooks]
postinstall = '''
  cd {{config_root|quote}} &&
  git lfs install --local &&
  git lfs pull &&
  uv sync
'''

[tasks]
local = "pyinfra -y @local deploy.py"
dry = "pyinfra --dry @local deploy.py"
