[tools]
python = "3.12"
uv = "0.10"

[settings]
experimental = true
python.uv_venv_auto = "create|source"

[env]
PROJECT_TOP = "{{config_root}}"

[hooks]
postinstall = '''
  cd "$PROJECT_TOP" &&
  git lfs install --local &&
  git lfs pull &&
  uv sync
'''

[tasks]
local = "pyinfra -y @local deploy.py"
dry = "pyinfra --dry @local deploy.py"
