#!/usr/bin/env python3
"""Regenerate dns/files/knot.conf.

Two zone lists, both hardcoded:

- PRIMARY: user-owned zones we master here. Each has a matching .zone file in
  dns/files/zones/. Adding to this list means also writing that zone file (see
  CLAUDE.md "Adding a zone to the Knot nameserver").

- OFB_SLAVES: the residual zones for which ofb.net's BIND is master AND whose
  published NS records (at the parent registry or in the zone's own apex NS
  set) still resolve to this host (104.200.25.248 / our v6 addresses) as
  `ns2.ofb.net` or `egnor-2020.ofb.net`. We AXFR from 104.197.242.163.
  The ns2.ofb.net role is being retired -- when this list goes empty, the
  ofb_slave template + ofb_master remote + ofb_notify ACL can all come out
  too, and Knot here becomes purely primary.

Was previously derived from ofb's `config.sh` (every `^master ...` line);
flipped to an explicit allowlist once we GC'd ofb's master.conf and audited
which surviving zones actually still need us.
"""

import os

HERE = os.path.dirname(os.path.realpath(__file__))
DST = os.path.join(HERE, "files", "knot.conf")

PRIMARY = [
    "amiobsoleteyet.com",
    "amiobsoleteyet.org",
    "amiobsoleteyet.net",
    "cara.vision",
    "competent.services",
    "eacs.io",
    "egnor.io",
    "egnor.services",
    "egnor.me",
    "escaperooms.fun",
    "gorey.games",
    "plague.wtf",
    "prexcytgo.com",
    "dan.egnor.name",
    "nutrimatic.org",
    "isthereapuzzlehuntthisweekend.com",
    "isthereapuzzlehunttoday.com",
    "isthereapuzzlehunttomorrow.com",
    "puzzlehuntcalendar.com",
    "puzzlehuntcalendar.org",
    "puzzlehunts.org",
    "teamleftout.org",
]

# ofb-mastered zones whose published delegation still routes traffic to us.
# Drop a zone from here once its parent NS records no longer list
# `egnor-2020.ofb.net` AND its in-zone apex NS set no longer lists
# `ns2.ofb.net` (or any glue name resolving to our IPs).
OFB_SLAVES = [
    # parent registrar NS still lists `egnor-2020.ofb.net` (apex NS at ofb has
    # been updated to list ns1.ofb.net + ns{2..5}.he.net; HE is active as
    # secondary). Comes off this list once the registrar NS records are flipped
    # to drop egnor-2020.ofb.net.
    "mandelson.org",
]

HEADER = """\
# Managed by pyinfra. Source: dns/files/knot.conf (regenerated by dns/gen_knot_conf.py)
# Knot DNS authoritative server for egnor-2020.
#
# Dual role:
#   1) Primary for user-owned zones (## primary zones below). Source-of-truth
#      zone files live in /etc/knot/zones/ from this repo. Hurricane Electric
#      (he_net) is the AXFR-pulling secondary, registered per-zone at
#      dns.he.net.
#   2) Secondary (ns2.ofb.net) for the residual ofb-mastered zones whose
#      published delegation still routes to us. Slaved from 104.197.242.163
#      (ns1.ofb.net). This role is being wound down -- see OFB_SLAVES in
#      gen_knot_conf.py.
#
# Reference: man knot.conf  /  https://www.knot-dns.cz/docs/3.3/html/

server:
    listen: 0.0.0.0@53
    listen: ::@53
    user: knot:knot
    rundir: /run/knot
    pidfile: /run/knot/knot.pid

log:
  - target: syslog
    any: info

# Hurricane Electric free-secondary service. Send NOTIFY to them, allow AXFR
# from them. Each primary zone is registered separately at dns.he.net.
remote:
  - id: he_net
    address: 216.218.130.2
    address: 216.218.131.2
    address: 216.218.132.2
    address: 216.66.1.2
    address: 216.66.80.18
    address: 2001:470:100::2
    address: 2001:470:200::2
    address: 2001:470:300::2
    address: 2001:470:400::2
    address: 2001:470:500::2

  # ofb.net master (ns1.ofb.net). We pull AXFR from it; it sends NOTIFY to us.
  - id: ofb_master
    address: 104.197.242.163

acl:
  - id: he_xfr
    # ns{1..5}.he.net IPs (documented at dns.he.net) -- these are where the
    # slaves actually serve queries from.
    address: 216.218.130.2
    address: 216.218.131.2
    address: 216.218.132.2
    address: 216.66.1.2
    address: 216.66.80.18
    address: 2001:470:100::2
    address: 2001:470:200::2
    address: 2001:470:300::2
    address: 2001:470:400::2
    address: 2001:470:500::2
    # 216.218.133.2 is HE.net's hidden AXFR-ingestion master -- observed in
    # tcpdump during signup but not in their documented list. Without it,
    # the slave-add fails with "make sure your nameservers allow AXFRs".
    address: 216.218.133.2
    action: transfer

  - id: ofb_notify
    address: 104.197.242.163
    action: notify

template:
  # Primary template: HE.net is the secondary.
  - id: default
    # `difference-no-serial` lets Knot detect content changes ignoring the
    # in-file SOA serial; it then bumps the serial itself per serial-policy.
    # This mode requires journal-content=all so Knot has the previous zone
    # state to diff against.
    zonefile-load: difference-no-serial
    journal-content: all
    serial-policy: unixtime
    acl: he_xfr
    notify: he_net

  # Secondary template: pull from ofb_master, accept NOTIFY from it. No
  # `file:` is set per zone -- Knot writes the AXFRed zone into its default
  # storage at /var/lib/knot/.
  - id: ofb_slave
    master: ofb_master
    acl: ofb_notify

zone:
## primary zones (user-owned)
"""

PRIMARY_BLOCK = """\
  - domain: {z}
    file: /etc/knot/zones/{z}.zone
    template: default
"""

SLAVE_BLOCK = """\
  - domain: {z}
    template: ofb_slave
"""

with open(DST, "w") as out:
    out.write(HEADER)
    for z in PRIMARY:
        out.write(PRIMARY_BLOCK.format(z=z))
    out.write("\n## secondary zones (ofb.net master at 104.197.242.163, ns2.ofb.net role -- being retired)\n")
    for z in OFB_SLAVES:
        out.write(SLAVE_BLOCK.format(z=z))

print(f"Wrote {len(PRIMARY)} primary + {len(OFB_SLAVES)} ofb-slave zones")
with open(DST) as f:
    print(f"{DST}: {sum(1 for _ in f)} lines")
