#!/usr/bin/env python3
"""Regenerate dns/files/knot.conf.

The primary-zone list (`PRIMARY`) is the set of user-owned zones we master
here — each has a matching .zone file in dns/files/zones/. The secondary-
zone list is derived from the live reference checkout of ofb.net's BIND
config (re-fetched manually whenever its master.conf is edited): every
uncommented `^master <zone> <file>` line, plus `dynamic.ofb.net` which
config.sh special-cases in its footer. Anything in PRIMARY gets filtered
out to avoid duplicate `zone:` entries.

After running, deploy via `pyinfra @local deploy.py` — or for a quick
out-of-band push, `sudo install -o root -g knot -m 640 dns/files/knot.conf
/etc/knot/knot.conf && sudo knotc reload`.
"""

import os
import re

HERE = os.path.dirname(os.path.realpath(__file__))
DST = os.path.join(HERE, "files", "knot.conf")

# Re-fetched manually from the actual ofb host whenever its config.sh is
# edited (this dir is a sibling of the dotfiles repo, not inside it).
OFB_CONFIG = "/home/egnor/reference/ofb_config_bind/config.sh"

# Primary zones: user-owned, mastered here. Each one has a corresponding
# .zone file in dns/files/zones/. Adding to this list means also writing
# that zone file (see CLAUDE.md "Adding a zone to the Knot nameserver").
PRIMARY = [
    "amiobsoleteyet.com",
    "amiobsoleteyet.org",
    "amiobsoleteyet.net",
    "cara.vision",
    "competent.services",
    "eacs.io",
    "egnor.io",
    "egnor.services",
    "egnor.me",
    "escaperooms.fun",
    "gorey.games",
    "plague.wtf",
    "prexcytgo.com",
    "dan.egnor.name",
    "nutrimatic.org",
    "isthereapuzzlehuntthisweekend.com",
    "isthereapuzzlehunttoday.com",
    "isthereapuzzlehunttomorrow.com",
    "puzzlehuntcalendar.com",
    "puzzlehuntcalendar.org",
    "puzzlehunts.org",
    "teamleftout.org",
]

# Derive the ofb-slave list from the reference config.sh.
_master_re = re.compile(r"^master\s+(\S+)\s+\S+")
ofb_raw = ["dynamic.ofb.net"]
with open(OFB_CONFIG) as f:
    for line in f:
        m = _master_re.match(line)
        if m:
            ofb_raw.append(m.group(1))
ofb_raw = sorted(set(ofb_raw))

# Dual-mastered zones (in both PRIMARY and ofb's master list) are filtered
# out — Knot rejects duplicate zone entries. The transitional split-brain
# resolves when the user updates ofb's config.sh to remove those zones.
OFB_SLAVES = [z for z in ofb_raw if z not in set(PRIMARY)]
overlap = sorted(set(PRIMARY) & set(ofb_raw))
print(f"Read {len(ofb_raw)} ofb-mastered zones from {OFB_CONFIG}")
if overlap:
    print(f"Filtered out {len(overlap)} dual-mastered (also in PRIMARY): {overlap}")
print(f"Final ofb slave count: {len(OFB_SLAVES)}")

HEADER = """\
# Managed by pyinfra. Source: dns/files/knot.conf (regenerated by dns/gen_knot_conf.py)
# Knot DNS authoritative server for egnor-2020.
#
# Dual role:
#   1) Primary for user-owned zones (## primary zones below). Source-of-truth
#      zone files live in /etc/knot/zones/ from this repo. Hurricane Electric
#      (he_net) is the AXFR-pulling secondary, registered per-zone at
#      dns.he.net.
#   2) Secondary (ns2.ofb.net) for ofb.net's remaining zones, slaved from the
#      master at 104.197.242.163 (ns1.ofb.net). Same role BIND9 previously
#      filled on this host; BIND is decommissioned now that Knot owns port 53.
#
# Reference: man knot.conf  /  https://www.knot-dns.cz/docs/3.3/html/

server:
    listen: 0.0.0.0@53
    listen: ::@53
    user: knot:knot
    rundir: /run/knot
    pidfile: /run/knot/knot.pid

log:
  - target: syslog
    any: info

# Hurricane Electric free-secondary service. Send NOTIFY to them, allow AXFR
# from them. Each primary zone is registered separately at dns.he.net.
remote:
  - id: he_net
    address: 216.218.130.2
    address: 216.218.131.2
    address: 216.218.132.2
    address: 216.66.1.2
    address: 216.66.80.18
    address: 2001:470:100::2
    address: 2001:470:200::2
    address: 2001:470:300::2
    address: 2001:470:400::2
    address: 2001:470:500::2

  # ofb.net master (ns1.ofb.net). We pull AXFR from it; it sends NOTIFY to us.
  - id: ofb_master
    address: 104.197.242.163

acl:
  - id: he_xfr
    # ns{1..5}.he.net IPs (documented at dns.he.net) — these are where the
    # slaves actually serve queries from.
    address: 216.218.130.2
    address: 216.218.131.2
    address: 216.218.132.2
    address: 216.66.1.2
    address: 216.66.80.18
    address: 2001:470:100::2
    address: 2001:470:200::2
    address: 2001:470:300::2
    address: 2001:470:400::2
    address: 2001:470:500::2
    # 216.218.133.2 is HE.net's hidden AXFR-ingestion master — observed in
    # tcpdump during signup but not in their documented list. Without it,
    # the slave-add fails with "make sure your nameservers allow AXFRs".
    address: 216.218.133.2
    action: transfer

  - id: ofb_notify
    address: 104.197.242.163
    action: notify

template:
  # Primary template: HE.net is the secondary.
  - id: default
    # `difference-no-serial` lets Knot detect content changes ignoring the
    # in-file SOA serial; it then bumps the serial itself per serial-policy.
    # This mode requires journal-content=all so Knot has the previous zone
    # state to diff against.
    zonefile-load: difference-no-serial
    journal-content: all
    serial-policy: unixtime
    acl: he_xfr
    notify: he_net

  # Secondary template: pull from ofb_master, accept NOTIFY from it. No
  # `file:` is set per zone — Knot writes the AXFRed zone into its default
  # storage at /var/lib/knot/.
  - id: ofb_slave
    master: ofb_master
    acl: ofb_notify

zone:
## primary zones (user-owned)
"""

PRIMARY_BLOCK = """\
  - domain: {z}
    file: /etc/knot/zones/{z}.zone
    template: default
"""

SLAVE_BLOCK = """\
  - domain: {z}
    template: ofb_slave
"""

with open(DST, "w") as out:
    out.write(HEADER)
    for z in PRIMARY:
        out.write(PRIMARY_BLOCK.format(z=z))
    out.write("\n## secondary zones (ofb.net master at 104.197.242.163, ns2.ofb.net role)\n")
    for z in OFB_SLAVES:
        out.write(SLAVE_BLOCK.format(z=z))

with open(DST) as f:
    print(f"{DST}: {sum(1 for _ in f)} lines")
