# Postfix MTA config for egnor-2020. Receives mail for personal +
# blackletterlabs.com / seventeengames.com / eacs.io /
# approximately.competent.services, signs outgoing via opendkim milter, and
# accepts authenticated submission via cyrus-sasl + sasldb.
#
# The sasldb itself (live secret, plaintext-equivalent passwords because of
# CRAM-MD5/DIGEST-MD5) is NOT in the repo — see CLAUDE.md for the
# saslpasswd2 workflow. /etc/sasldb2 is symlinked to the chroot copy so the
# cyrus-sasl tools (which default to /etc/sasldb2) work unmodified.

from pyinfra import host
from pyinfra.facts.server import Hostname
from pyinfra.operations import files, server, systemd
from pyinfra.operations.util import any_changed

if host.get_fact(Hostname) == "egnor-2020":
    # /etc/aliases is intentionally inert here (see postfix/files/aliases for
    # the full explanation). The file ships only for documentation, isn't in
    # alias_maps, and shouldn't be hashed — so no newaliases trigger, and any
    # leftover /etc/aliases.db from a previous deploy is removed.
    files.put(
        name="postfix: /etc/aliases (inert, see file header)",
        src="postfix/files/aliases",
        dest="/etc/aliases",
        mode="644",
        _sudo=True,
    )

    files.file(
        name="postfix: remove stale /etc/aliases.db",
        path="/etc/aliases.db",
        present=False,
        _sudo=True,
    )

    config_updates = [
        files.put(
            name="postfix: aliases_regexp",
            src="postfix/files/aliases_regexp",
            dest="/etc/postfix/aliases_regexp",
            mode="644",
            _sudo=True,
        ),

        files.put(
            name="postfix: /etc/mailname",
            src="postfix/files/mailname",
            dest="/etc/mailname",
            mode="644",
            _sudo=True,
        ),

        files.put(
            name="postfix: main.cf",
            src="postfix/files/main.cf",
            dest="/etc/postfix/main.cf",
            mode="644",
            _sudo=True,
        ),

        files.put(
            name="postfix: master.cf",
            src="postfix/files/master.cf",
            dest="/etc/postfix/master.cf",
            mode="644",
            _sudo=True,
        ),

        files.put(
            name="postfix: sasl/smtpd.conf",
            src="postfix/files/sasl/smtpd.conf",
            dest="/etc/postfix/sasl/smtpd.conf",
            mode="644",
            _sudo=True,
        ),

        virtual_update := files.put(
            name="postfix: virtual (alias map source)",
            src="postfix/files/virtual",
            dest="/etc/postfix/virtual",
            mode="644",
            _sudo=True,
        ),
    ]

    # cyrus-sasl tools default to /etc/sasldb2; postfix (chrooted) reads
    # /var/spool/postfix/etc/sasldb2. Symlink so they're the same file —
    # `saslpasswd2 -c -u <realm> <user>` then takes effect immediately,
    # no separate sync step needed (sasldb is read per-auth anyway).
    files.link(
        name="postfix: /etc/sasldb2 → chroot copy",
        path="/etc/sasldb2",
        target="/var/spool/postfix/etc/sasldb2",
        _sudo=True,
    )

    # /etc/postfix/virtual.db is generated by postmap; rebuild on source change.
    server.shell(
        name="postfix: postmap virtual",
        commands=["postmap /etc/postfix/virtual"],
        _sudo=True,
        _if=virtual_update.did_change,
    )

    systemd.service(
        name="postfix: reload on config change",
        service="postfix.service",
        reloaded=True,
        _sudo=True,
        _if=any_changed(*config_updates),
    )
