# Postfix MTA config for egnor-2020. Receives mail for personal +
# blackletterlabs.com / seventeengames.com / eacs.io /
# approximately.competent.services, signs outgoing via opendkim milter, and
# accepts authenticated submission via cyrus-sasl + sasldb.
#
# The sasldb itself (live secret, plaintext-equivalent passwords because of
# CRAM-MD5/DIGEST-MD5) is NOT in the repo — see CLAUDE.md for the
# saslpasswd2 workflow. /etc/sasldb2 is symlinked to the chroot copy so the
# cyrus-sasl tools (which default to /etc/sasldb2) work unmodified.

from pyinfra import host
from pyinfra.facts.server import Hostname
from pyinfra.operations import files, server, systemd
from pyinfra.operations.util import any_changed

if host.get_fact(Hostname) == "egnor-2020":
    main_cf = files.put(
        name="postfix: main.cf",
        src="postfix/files/main.cf",
        dest="/etc/postfix/main.cf",
        mode="644",
        _sudo=True,
    )

    master_cf = files.put(
        name="postfix: master.cf",
        src="postfix/files/master.cf",
        dest="/etc/postfix/master.cf",
        mode="644",
        _sudo=True,
    )

    aliases_regexp = files.put(
        name="postfix: aliases_regexp",
        src="postfix/files/aliases_regexp",
        dest="/etc/postfix/aliases_regexp",
        mode="644",
        _sudo=True,
    )

    virtual = files.put(
        name="postfix: virtual (alias map source)",
        src="postfix/files/virtual",
        dest="/etc/postfix/virtual",
        mode="644",
        _sudo=True,
    )

    # /etc/postfix/virtual.db is generated by postmap; rebuild on source change.
    server.shell(
        name="postfix: postmap virtual",
        commands=["postmap /etc/postfix/virtual"],
        _sudo=True,
        _if=virtual.did_change,
    )

    sasl_smtpd = files.put(
        name="postfix: sasl/smtpd.conf",
        src="postfix/files/sasl/smtpd.conf",
        dest="/etc/postfix/sasl/smtpd.conf",
        mode="644",
        _sudo=True,
    )

    mailname = files.put(
        name="postfix: /etc/mailname",
        src="postfix/files/mailname",
        dest="/etc/mailname",
        mode="644",
        _sudo=True,
    )

    aliases = files.put(
        name="postfix: /etc/aliases",
        src="postfix/files/aliases",
        dest="/etc/aliases",
        mode="644",
        _sudo=True,
    )

    server.shell(
        name="postfix: newaliases",
        commands=["newaliases"],
        _sudo=True,
        _if=aliases.did_change,
    )

    # cyrus-sasl tools default to /etc/sasldb2; postfix (chrooted) reads
    # /var/spool/postfix/etc/sasldb2. Symlink so they're the same file —
    # `saslpasswd2 -c -u <realm> <user>` then takes effect immediately,
    # no separate sync step needed (sasldb is read per-auth anyway).
    files.link(
        name="postfix: /etc/sasldb2 → chroot copy",
        path="/etc/sasldb2",
        target="/var/spool/postfix/etc/sasldb2",
        _sudo=True,
    )

    systemd.service(
        name="postfix: reload on config change",
        service="postfix.service",
        reloaded=True,
        _sudo=True,
        _if=any_changed(
            main_cf, master_cf, aliases_regexp, virtual,
            sasl_smtpd, mailname, aliases,
        ),
    )
