# Managed by pyinfra. Source: dotfiles/postfix/files/fix-chroot-resolv.conf
#
# Drop in *after* stock postfix@.service copies resolv.conf into its chroot,
# to replace the copy with a static file to avoid post-update race conditions.
#
# glibc honors 3 nameservers (MAXNS), we pick these:
#   173.230.145.5 - linode recursive, it's closest and can do DNSBL lookups
#   1.1.1.1 - cloudflare, standby
#   8.8.8.8 - google, standby

[Service]
ExecStartPre=/usr/bin/python3 -c "ns = '173.230.145.5 1.1.1.1 8.8.8.8'; \
content = ''.join(f'nameserver {s}\\n' for s in ns.split()); \
content += 'options timeout:2 attempts:2\\n'; \
open('/var/spool/postfix/etc/resolv.conf', 'w').write(content) \
"
