# Managed by pyinfra. Source: dotfiles/netdata/files.parent/netdata-alarm-notify-env.conf
#
# Environment for netdata, inherited by alarm-notify.sh when netdata execs it.
# Sets variables that can't be set in other ways.

[Service]
Environment="clear_alarm_always=YES"
