# postsrsd Sender Rewriting Scheme daemon for egnor-2020. Wired into
# postfix's {sender,recipient}_canonical_maps so mail FORWARDED through
# this host (e.g. external → root@eacs.io → egnor@ofb.net, or external →
# admin@blackletterlabs.com → drain.teaser@gmail.com) gets its
# envelope-from rewritten to an SRS-encoded @eacs.io address. Preserves
# SPF alignment across forward boundaries without forging the original
# sender's domain.
#
# The HMAC secret at /etc/postsrsd.secret is generated by the Debian
# package on first install (mode 0600, owner=postsrs) and stays out of
# the repo — leaking it would let an attacker forge SRS envelope-from
# addresses that decode to arbitrary bounce recipients.

from pyinfra import host
from pyinfra.facts.server import Hostname
from pyinfra.operations import files, systemd

if host.get_fact(Hostname) == "egnor-2020":
    config = files.put(
        name="postsrsd: /etc/default/postsrsd",
        src="postsrsd/files/postsrsd",
        dest="/etc/default/postsrsd",
        mode="644",
        _sudo=True,
    )

    systemd.service(
        name="postsrsd: restart on config change",
        service="postsrsd.service",
        restarted=True,
        _sudo=True,
        _if=config.did_change,
    )
