# Managed by pyinfra. Source: dotfiles/netdata/files.child/go.d/filecheck.conf
#
# Watch the unattended-upgrades success stamp written by apt.systemd.daily.
# See netdata/files.parent/health.d/apt_ugprade.conf for alerting logic.
# See netdata/files.parent/go.d/filecheck.conf for the parent version.

jobs:
  - name: apt_upgrade_stamp
    files:
      include:
        - '/var/lib/apt/periodic/upgrade-stamp'
