# Managed by pyinfra. Source: dotfiles/netdata/files.parent/health.d/httpcheck.conf
#
# Per-template overrides for stock httpcheck alerts.
#
# Use hysteresis on the average rather than time delays to prevent flapping
# while sidestepping issues with missed alerts due to delay scheduling.

# Replacement for default template that filters out noisy endpoints
    template: httpcheck_web_service_bad_status
          on: httpcheck.status
       class: Workload
        type: Web Server
   component: HTTP endpoint
chart labels: url=!https://shop.seventeengames.com *
      lookup: average -5m unaligned percentage of bad_status
       every: 10s
       units: %
        warn: $this >= (($status >= $WARNING)  ? (15) : (20)) AND $this < (($status == $CRITICAL) ? (35) : (40))
        crit: $this >= (($status == $CRITICAL) ? (35) : (40))
     summary: HTTP check for ${label:url} unexpected status
        info: Percentage of HTTP responses from ${label:url} with unexpected status in the last 5 minutes
          to: webmaster

# Alert for noisy endpoints not included above; has a much larger delay
    template: httpcheck_web_service_bad_status_noisy_endpoints
          on: httpcheck.status
       class: Workload
        type: Web Server
   component: HTTP endpoint
chart labels: url=https://shop.seventeengames.com
      lookup: average -30m unaligned percentage of bad_status
       every: 30s
       units: %
        warn: $this >= (($status >= $WARNING)  ? (15) : (20)) AND $this < (($status == $CRITICAL) ? (35) : (40))
        crit: $this >= (($status == $CRITICAL) ? (35) : (40))
     summary: HTTP check for ${label:url} unexpected status
        info: Percentage of HTTP responses from ${label:url} with unexpected status in the last 30 minutes
          to: webmaster
