# Managed by pyinfra. Source: dotfiles/netdata/files.parent/health.d/httpcheck.conf
# Per-template overrides for stock httpcheck alerts.

# Replacement for default template that filters out noisy endpoints
    template: httpcheck_web_service_bad_status
          on: httpcheck.status
       class: Workload
        type: Web Server
   component: HTTP endpoint
chart labels: url=!https://shop.seventeengames.com *
      lookup: average -5m unaligned percentage of bad_status
       every: 10s
       units: %
        warn: $this >= 20 AND $this < 40
        crit: $this >= 40
       delay: down 5m multiplier 1.5 max 1h
     summary: HTTP check for ${label:url} unexpected status
        info: Percentage of HTTP responses from ${label:url} with unexpected status in the last 5 minutes
          to: webmaster

# Alert for noisy endpoints not included above; has a much larger delay
    template: httpcheck_web_service_bad_status_noisy_endpoints
          on: httpcheck.status
       class: Workload
        type: Web Server
   component: HTTP endpoint
chart labels: url=https://shop.seventeengames.com
      lookup: average -30m unaligned percentage of bad_status
       every: 30s
       units: %
        warn: $this >= 20 AND $this < 40
        crit: $this >= 40
       delay: down 30m
     summary: HTTP check for ${label:url} unexpected status
        info: Percentage of HTTP responses from ${label:url} with unexpected status in the last 30 minutes
          to: webmaster
