# Managed by pyinfra. Source: dotfiles/netdata/files.parent/go.d/filecheck.conf
#
# Watch the success markers left by website probers, unattended upgrades, etc.

jobs:
  # See netdata/files.parent/health.d/iap_prober.conf for alerting logic.
  - name: iap_prober
    files:
      include:
        - '/home/egnor/prod-blackletterlabs-iap/prober_data/last_ok.txt'

  # See netdata/files.parent/health.d/iap_prober.conf for alerting logic.
  # See netdata/files.child/go.d/filecheck.conf for the child version.
  - name: apt_upgrade_stamp
    files:
      include:
        - '/var/lib/apt/periodic/upgrade-stamp'
