# Managed by pyinfra. Source: dotfiles/netdata/files.parent/go.d/smartctl.conf
#
# Enable netdata's SMART collector on physical hosts.
# See netdata/files.parent/health.d/smartctl.conf for alerting logic.
# See netdata/files.child/go.d/smartctl.conf for the child version.

jobs:
  - name: smartctl
